spring.application.name=analytics-service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=analytics-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Map the same key to the Consumer's local class
spring.kafka.consumer.properties.spring.json.type.mapping=patient_event:com.lc.analyticsservice.model.PatientEvent
# Trusted packages is required for security when deserializing
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.lc.patient_service.model.PatientEvent,com.lc.kafkaconsumertest.PatientEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#logging.level.org.apache.kafka=DEBUG
#logging.level.org.springframework.kafka=DEBUG

server.port=8083
